<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>VmAgent</RootNamespace>
    <AssemblyName>VmAgent</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="VmAgent.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="VmAgent.Tests\**" />
    <Content Remove="VmAgent.Tests\**" />
    <None Remove="VmAgent.Tests\**" />
    <EmbeddedResource Remove="VmAgent.Tests\**" />
  </ItemGroup>
</Project>

