using System.Collections.Generic;

namespace RatAnalyzer.Desktop.Localization;

/// <summary>Strings de logs de arranque e análise (PT/EN).</summary>
internal static class LogCatalog
{
    public static void MergeInto(Dictionary<string, string> pt, Dictionary<string, string> en)
    {
        foreach (var (k, v) in Pt()) pt[k] = v;
        foreach (var (k, v) in En()) en[k] = v;
    }

    private static Dictionary<string, string> Pt() => new()
    {
        [LocKeys.LogDepsStart] = "[INFO] === Dependências: análise estática + VM (verificação / instalação) ===",
        [LocKeys.LogBackendNotFound] = "[AVISO] Pasta 'backend' não encontrada a partir do executável — pip em falta.",
        [LocKeys.LogBackendOk] = "[OK] Pasta backend: {0}",
        [LocKeys.LogBackendPipError] = "[ERRO] Dependências Python (pip): {0}",
        [LocKeys.LogFrontendNotFound] = "[AVISO] Pasta 'frontend' não encontrada — npm em falta.",
        [LocKeys.LogFrontendOk] = "[OK] Pasta frontend: {0}",
        [LocKeys.LogFrontendNpmError] = "[ERRO] Dependências npm: {0}",
        [LocKeys.LogOscdimgOk] = "[OK] oscdimg.exe (Windows ADK): {0}",
        [LocKeys.LogOscdimgMissing] = "[AVISO] oscdimg.exe em falta — necessário para criar ISO com autounattend (VM). Instale o Windows ADK (Deployment Tools).",
        [LocKeys.LogHypervScriptsOk] = "[OK] scripts/hyperv-sandbox: {0}",
        [LocKeys.LogHypervScriptsMissing] = "[AVISO] scripts/hyperv-sandbox não encontrado — análise VM Hyper-V pode falhar.",
        [LocKeys.LogJavaWarning] = "[AVISO] Java JDK: {0}",
        [LocKeys.LogIlspyWarning] = "[AVISO] ILSpy CLI: {0}",
        [LocKeys.LogGhidraWarning] = "[AVISO] Ghidra: {0}",
        [LocKeys.LogDepsEnd] = "[INFO] === Fim dependências; a abrir serviços nas portas 8000 e 8080 ===",
        [LocKeys.LogExecFailed] = "[ERRO] {0}: não foi possível iniciar '{1}'.",
        [LocKeys.LogExecOk] = "[OK] {0}",
        [LocKeys.LogExecOkDetail] = "[OK] {0}: {1}",
        [LocKeys.LogExecExitCode] = "[ERRO] {0}: '{1}' saiu com código {2}. {3}",
        [LocKeys.LogExecError] = "[ERRO] {0}: {1}",
        [LocKeys.LogPythonFailed] = "[ERRO] {0}: não foi possível executar python.",
        [LocKeys.LogPythonOk] = "[OK] {0}",
        [LocKeys.LogPythonCheckFailed] = "[AVISO] {0}: falhou (código {1}). {2}",
        [LocKeys.LogYaraNativeHint] = "[INFO] YARA: instale a biblioteca nativa (Windows) além do pip — ver README do projeto.",
        [LocKeys.LogHypervPsFailed] = "[AVISO] Hyper-V: não foi possível executar PowerShell.",
        [LocKeys.LogHypervStateFailed] = "[AVISO] Hyper-V: não foi possível ler o estado (executar como Administrador?).",
        [LocKeys.LogHypervEnabled] = "[OK] Hyper-V (Microsoft-Hyper-V): Enabled",
        [LocKeys.LogHypervUnknown] = "[AVISO] Hyper-V: estado desconhecido (edição Windows Home não inclui Hyper-V?).",
        [LocKeys.LogHypervState] = "[AVISO] Hyper-V: estado '{0}' — necessário Enabled para VM local (reinício após Enable-WindowsOptionalFeature).",
        [LocKeys.LogHypervError] = "[AVISO] Hyper-V: {0}",
        [LocKeys.LogDepsPhaseWarning] = "[AVISO] Fase de dependências: {0}",
        [LocKeys.LogBackendChecking] = "[INFO] A verificar backend em http://localhost:8000 ...",
        [LocKeys.LogBackendStarting] = "[INFO] Backend não encontrado. A iniciar servidor uvicorn...",
        [LocKeys.LogBackendStarted] = "[OK] Backend iniciado com sucesso em http://localhost:8000.",
        [LocKeys.LogBackendAlreadyRunning] = "[OK] Backend já se encontra em execução.",
        [LocKeys.LogFrontendChecking] = "[INFO] A verificar dev server do frontend...",
        [LocKeys.LogFrontendReady] = "[OK] Frontend pronto.",
        [LocKeys.LogReqLockMissing] = "[AVISO] requirements.lock em falta — a usar requirements.txt (menos reproduzível).",
        [LocKeys.LogReqFilesMissing] = "[AVISO] Ficheiros requirements.lock / requirements.txt não encontrados; a saltar pip install.",
        [LocKeys.LogPipEnsure] = "[INFO] A garantir dependências Python (pip)…",
        [LocKeys.LogPipOk] = "[OK] Dependências Python verificadas/instaladas.",
        [LocKeys.LogNpmInstall] = "[INFO] node_modules incompletos ou em falta. A executar npm install…",
        [LocKeys.LogNpmOk] = "[OK] Dependências npm instaladas.",
        [LocKeys.LogProdTokenWarning] = "[AVISO] Modo produção/estrito activo mas RATANALYZER_API_TOKEN não definido — o backend pode recusar arrancar. Veja docs/production-secrets.md.",
        [LocKeys.LogStaticRegister] = "A registar análise estática em curso no backend...",
        [LocKeys.LogStaticAnalyzing] = "A analisar ficheiro (Ghidra / YARA / IL)...",
        [LocKeys.LogStaticPublishing] = "A publicar resultados no backend...",
        [LocKeys.LogStaticDone] = "Análise estática concluída e registada no backend.",
        [LocKeys.LogDynamicRegister] = "A registar análise dinâmica em curso no backend...",
        [LocKeys.LogDynamicPublish] = "A enviar relatório da VM para o frontend...",
        [LocKeys.LogBackendServiceStart] = "A iniciar servidor backend (uvicorn)...",
    };

    private static Dictionary<string, string> En() => new()
    {
        [LocKeys.LogDepsStart] = "[INFO] === Dependencies: static analysis + VM (check / install) ===",
        [LocKeys.LogBackendNotFound] = "[WARN] 'backend' folder not found from executable — pip skipped.",
        [LocKeys.LogBackendOk] = "[OK] Backend folder: {0}",
        [LocKeys.LogBackendPipError] = "[ERROR] Python dependencies (pip): {0}",
        [LocKeys.LogFrontendNotFound] = "[WARN] 'frontend' folder not found — npm skipped.",
        [LocKeys.LogFrontendOk] = "[OK] Frontend folder: {0}",
        [LocKeys.LogFrontendNpmError] = "[ERROR] npm dependencies: {0}",
        [LocKeys.LogOscdimgOk] = "[OK] oscdimg.exe (Windows ADK): {0}",
        [LocKeys.LogOscdimgMissing] = "[WARN] oscdimg.exe missing — required to create ISO with autounattend (VM). Install Windows ADK (Deployment Tools).",
        [LocKeys.LogHypervScriptsOk] = "[OK] scripts/hyperv-sandbox: {0}",
        [LocKeys.LogHypervScriptsMissing] = "[WARN] scripts/hyperv-sandbox not found — Hyper-V VM analysis may fail.",
        [LocKeys.LogJavaWarning] = "[WARN] Java JDK: {0}",
        [LocKeys.LogIlspyWarning] = "[WARN] ILSpy CLI: {0}",
        [LocKeys.LogGhidraWarning] = "[WARN] Ghidra: {0}",
        [LocKeys.LogDepsEnd] = "[INFO] === Dependencies done; starting services on ports 8000 and 8080 ===",
        [LocKeys.LogExecFailed] = "[ERROR] {0}: could not start '{1}'.",
        [LocKeys.LogExecOk] = "[OK] {0}",
        [LocKeys.LogExecOkDetail] = "[OK] {0}: {1}",
        [LocKeys.LogExecExitCode] = "[ERROR] {0}: '{1}' exited with code {2}. {3}",
        [LocKeys.LogExecError] = "[ERROR] {0}: {1}",
        [LocKeys.LogPythonFailed] = "[ERROR] {0}: could not run python.",
        [LocKeys.LogPythonOk] = "[OK] {0}",
        [LocKeys.LogPythonCheckFailed] = "[WARN] {0}: failed (code {1}). {2}",
        [LocKeys.LogYaraNativeHint] = "[INFO] YARA: install the native library (Windows) in addition to pip — see project README.",
        [LocKeys.LogHypervPsFailed] = "[WARN] Hyper-V: could not run PowerShell.",
        [LocKeys.LogHypervStateFailed] = "[WARN] Hyper-V: could not read state (run as Administrator?).",
        [LocKeys.LogHypervEnabled] = "[OK] Hyper-V (Microsoft-Hyper-V): Enabled",
        [LocKeys.LogHypervUnknown] = "[WARN] Hyper-V: unknown state (Windows Home edition does not include Hyper-V?).",
        [LocKeys.LogHypervState] = "[WARN] Hyper-V: state '{0}' — Enabled required for local VM (reboot after Enable-WindowsOptionalFeature).",
        [LocKeys.LogHypervError] = "[WARN] Hyper-V: {0}",
        [LocKeys.LogDepsPhaseWarning] = "[WARN] Dependency phase: {0}",
        [LocKeys.LogBackendChecking] = "[INFO] Checking backend at http://localhost:8000 ...",
        [LocKeys.LogBackendStarting] = "[INFO] Backend not found. Starting uvicorn server...",
        [LocKeys.LogBackendStarted] = "[OK] Backend started at http://localhost:8000.",
        [LocKeys.LogBackendAlreadyRunning] = "[OK] Backend is already running.",
        [LocKeys.LogFrontendChecking] = "[INFO] Checking frontend dev server...",
        [LocKeys.LogFrontendReady] = "[OK] Frontend ready.",
        [LocKeys.LogReqLockMissing] = "[WARN] requirements.lock missing — using requirements.txt (less reproducible).",
        [LocKeys.LogReqFilesMissing] = "[WARN] requirements.lock / requirements.txt not found; skipping pip install.",
        [LocKeys.LogPipEnsure] = "[INFO] Ensuring Python dependencies (pip)…",
        [LocKeys.LogPipOk] = "[OK] Python dependencies verified/installed.",
        [LocKeys.LogNpmInstall] = "[INFO] node_modules incomplete or missing. Running npm install…",
        [LocKeys.LogNpmOk] = "[OK] npm dependencies installed.",
        [LocKeys.LogProdTokenWarning] = "[WARN] Production/strict mode active but RATANALYZER_API_TOKEN is not set — backend may refuse to start. See docs/production-secrets.md.",
        [LocKeys.LogStaticRegister] = "Registering static analysis with backend...",
        [LocKeys.LogStaticAnalyzing] = "Analyzing file (Ghidra / YARA / IL)...",
        [LocKeys.LogStaticPublishing] = "Publishing results to backend...",
        [LocKeys.LogStaticDone] = "Static analysis complete and registered on backend.",
        [LocKeys.LogDynamicRegister] = "Registering dynamic analysis with backend...",
        [LocKeys.LogDynamicPublish] = "Sending VM report to frontend...",
        [LocKeys.LogBackendServiceStart] = "Starting backend server (uvicorn)...",
    };
}
